// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVTrW-u35YoCrtc8wUjIcvQpjCEi5TZqA',
    appId: '1:951287145364:web:d45774f57367dc99dbe581',
    messagingSenderId: '951287145364',
    projectId: 'mobiledevelopment-ed0ab',
    authDomain: 'mobiledevelopment-ed0ab.firebaseapp.com',
    databaseURL: 'https://mobiledevelopment-ed0ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobiledevelopment-ed0ab.appspot.com',
    measurementId: 'G-VRL1FPFJV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvdbSIvbHCSkjzPnEQFg96iBwtUgXHYng',
    appId: '1:951287145364:android:0b4e43ab94b11602dbe581',
    messagingSenderId: '951287145364',
    projectId: 'mobiledevelopment-ed0ab',
    databaseURL: 'https://mobiledevelopment-ed0ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobiledevelopment-ed0ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAerUe3a9_LRfYEBQd3Gq97gZNayR5eSLo',
    appId: '1:951287145364:ios:a4818081b6f7425edbe581',
    messagingSenderId: '951287145364',
    projectId: 'mobiledevelopment-ed0ab',
    databaseURL: 'https://mobiledevelopment-ed0ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobiledevelopment-ed0ab.appspot.com',
    iosClientId: '951287145364-18i01jh3mf0b81d8irocq1m174kdm142.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAppTravistax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAerUe3a9_LRfYEBQd3Gq97gZNayR5eSLo',
    appId: '1:951287145364:ios:a4818081b6f7425edbe581',
    messagingSenderId: '951287145364',
    projectId: 'mobiledevelopment-ed0ab',
    databaseURL: 'https://mobiledevelopment-ed0ab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobiledevelopment-ed0ab.appspot.com',
    iosClientId: '951287145364-18i01jh3mf0b81d8irocq1m174kdm142.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAppTravistax',
  );
}
